title: sleepy boys club
description: a philosophy and being kind club
# email: your-email@address.com

author: sleepy boys club #  Default is your site title.

# Your social accounts.
social:
  github: sleepyboysclub
  
# Theme Settings

remote_theme: erlzhang/jekyll-theme-persephone
# Your site's logo. Will be shown on the left top of your page.
# logo: /img/okaykoa_logo.jpg
# If the images of our blog are stored in an external cloud. You can use the jekyll-img-prefix plugin and set your images' base URL here.
# img_prefix: https://your-img-cdn.com
# # The RSS link of your blog.
# rss: "/feed.xml"

# The followings are settings for displays of your blog.
theme_setting:
  # # The slides count in the slides layout. Default is 4.
  # slides_count: 5
  # The ← back URL on the top of your post page. Default is your site's home page.
  blog_page: "pages/blog.md"
  # The ← back URL on the top of your post page. Default is your site's home page.
  about_page: "index.md"
  # #  The URL of the menu icon(which has three black lines). Will be shown on the slides/book/chapter layouts It won't be shown if blank.
  # archive_page: "archive.md"
  # The nav links on the top right of home/page/post/blog layout. You can set a local page(by setting a layout's path) or and external link ( both title and url are required) here.
  nav_pages:
    - "pages/archive.md"
    - "index.md"
    # -
    #   title: "External Link Title"
    #   url: "https://your-external-link.com"
  # Every default value in the following settings is false. You can set them globally here or separately in a single post/page/chapter.
  # code: true # Code highlight.
  # math: true # Mathjax
  # mermaid: true # Mermaid
  #  Locales of this theme.
  # lang:
    # category_all: all entries # The first tag in the categories bar on the blog layout page. By clicking it all of your posts will be shown. Default is 'All'.
    # blog_title: posts # The text of ← back url on the top of the post layout.  Default is 'Home'.
    # # The locales of the comment controls.
    # comment:
    #   user: "昵称"
    #   email: "邮箱"
    #   url: "链接"
    #   message: "说点什么吧..."
    #   reply: "回复"

# head_code: |
#   <!-- Extra codes in the head of your site pages. You can add your Google Analysis codes here! -->

# The settings of comments.
# comment:
#   # You should set it to enable comment
#   enabled: true
#   # Your comment provider
#   provider: disqus # static/disqus
#   # If provider == disqus
#   disqus:
#     name: website_name
#   # Or provider == static
#   static:
#     # Your static comment url.
#     postUrl:  https://api.staticman.net/v2/connect/GITHUB-USERNAME/GITHUB-REPOSITORY
# # The settings of local smileys used in static comments. The jekyll-smiley plugin is required.
smiley:
  enabled: true
  dir: img/smileys
